title = "gitleaks config"
# add regexes to the regex table
[[rules]]
description = "AWS"
regex = '''AKIA[0-9A-Z]{16}'''
[[rules]]
description = "PKCS8"
regex = '''-----BEGIN PRIVATE KEY-----'''
[[rules]]
description = "RSA"
regex = '''-----BEGIN RSA PRIVATE KEY-----'''
[[rules]]
description = "SSH"
regex = '''-----BEGIN OPENSSH PRIVATE KEY-----'''
[[rules]]
description = "PGP"
regex = '''-----BEGIN PGP PRIVATE KEY BLOCK-----'''
[[rules]]
description = "Facebook"
regex = '''(?i)facebook(.{0,4})?['\"][0-9a-f]{32}['\"]'''
[[rules]]
description = "Twitter"
regex = '''(?i)twitter(.{0,4})?['\"][0-9a-zA-Z]{35,44}['\"]'''
[[rules]]
description = "GitHub"
regex = '''(?i)github(.{0,4})?['\"][0-9a-zA-Z]{35,40}['\"]'''
[[rules]]
description = "Shopify shared secret"
regex = '''shpss_[a-fA-F0-9]{32}'''
[[rules]]
description = "Shopify access token"
regex = '''shpat_[a-fA-F0-9]{32}'''
[[rules]]
description = "Shopify custom app access token"
regex = '''shpca_[a-fA-F0-9]{32}'''
[[rules]]
description = "Shopify private app access token"
regex = '''shppa_[a-fA-F0-9]{32}'''
[[rules]]
description = "Slack Token"
regex = '''xox[baprs]-([0-9a-zA-Z]{10,48})?'''
[[rules]]
description = "Stripe"
regex = '''(?i)(sk|pk)_(test|live)_[0-9a-zA-Z]{10,32}'''
[[rules]]
description = "Generic API Key"
regex = '''(?i)api[-_]?(key|token)\s*:?=\s*['\"][0-9a-zA-Z-_/]{8,40}['\"]'''
[whitelist]
file = "(.*?)(jpg|gif|doc|pdf|bin|svg|socket)$"

# rules from trufflehog
# TODO remove wildcards... that could be expensive
[[rules]]
description = "Google (GCP) Service-account"
regex = '''\"type\": \"service_account\"'''
[[rules]]
description = "Heroku API Key"
regex = '''(?i)heroku.*[0-9A-F]{8}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{4}-[0-9A-F]{12}'''
[[rules]]
# demo of this regex not matching passwords in urls that contain env vars:
# https://regex101.com/r/rT9Lv9/3
description = "Password in URL"
regex = '''[a-zA-Z]{3,10}:\/\/[^$][^:@]{3,20}:[^$][^:@]{3,40}@.{1,100}'''
[[rules]]
description = "SSH (DSA) private key"
regex = '''-----BEGIN DSA PRIVATE KEY-----'''
[[rules]]
description = "SSH (EC) private key"
regex = '''-----BEGIN EC PRIVATE KEY-----'''
[[rules]]
description = "Slack Webhook"
regex = '''https://hooks.slack.com/services/T[a-zA-Z0-9_]{8}/B[a-zA-Z0-9_]{8}/[a-zA-Z0-9_]{24}'''
[[rules]]
description = "Twilio API Key"
regex = '''SK[0-9a-fA-F]{32}'''
[[rules]]
description = "Social Security Number"
regex = '''\d{3}-\d{2}-\d{4}'''
[rules.allowlist]
description = "allow listed social security numbers"
regexes = ['''219-09-9999''', '''078-05-1120''', '''(9[0-9]{2}|666)-\d{2}-\d{4}''']
